(()=>{const c=document.querySelector("[data-cosmos-launcher]");if(!c||typeof HTMLDialogElement>"u")return;const g="The playground could not start. Please close it and try again.";let a="",s=0,l=null,i=0;function n(){a="",s=0}function u(t,e){const o=e.map(r=>[r,t.style.getPropertyValue(r),t.style.getPropertyPriority(r)]);return()=>o.forEach(([r,b,v])=>{b?t.style.setProperty(r,b,v):t.style.removeProperty(r)})}function d(t){if(l!==t)return;l=null,n(),t.abort.abort(),t.playground?.dispose(),t.dialog.close(),t.dialog.remove(),t.restoreBody(),t.restoreRoot();const e=t.invoker?.isConnected?t.invoker:document.body,o=e.getAttribute("tabindex");e===document.body&&e.setAttribute("tabindex","-1"),e.focus({preventScroll:!0}),e===document.body&&(o===null?e.removeAttribute("tabindex"):e.setAttribute("tabindex",o)),window.scrollTo({left:t.x,top:t.y,behavior:"instant"})}function m(){n();const t=document.createElement("dialog");t.className="cosmos-dialog cosmos-prompt",t.setAttribute("aria-labelledby","cosmos-title"),t.innerHTML=`<header class="cosmos-heading">
      <div><p class="cosmos-prompt-label">~/cosmos</p><h2 id="cosmos-title">Command prompt</h2></div>
      <button type="button" class="cosmos-close" aria-label="Close">Close <span aria-hidden="true">[esc]</span></button>
      </header><div class="cosmos-content"></div>`;const e={dialog:t,host:t.querySelector(".cosmos-content"),abort:new AbortController,invoker:document.activeElement,x:scrollX,y:scrollY,playground:null,state:"prompt",restoreBody:u(document.body,["position","top","left","right","width","overflow"]),restoreRoot:u(document.documentElement,["overflow"])};l=e,document.body.append(t);try{document.body.style.position="fixed",document.body.style.top=`${-e.y}px`,document.body.style.left=`${-e.x}px`,document.body.style.right="0",document.body.style.width="100%",document.body.style.overflow="hidden",document.documentElement.style.overflow="hidden",t.showModal()}catch(r){throw d(e),r}const o={signal:e.abort.signal};return t.querySelector(".cosmos-close").addEventListener("click",()=>d(e),o),t.addEventListener("cancel",r=>{r.preventDefault(),e.playground?.cancelAim()||d(e)},o),t.addEventListener("close",()=>d(e),o),e}function p(t){if(l!==t)return;t.playground?.dispose(),t.playground=null,t.state="error",t.host.replaceChildren();const e=document.createElement("p");e.className="cosmos-message",e.setAttribute("role","alert"),e.textContent=g,t.host.append(e),t.dialog.querySelector(".cosmos-close").focus({preventScroll:!0})}async function y(t=null){if(!(!t&&l)&&(t??=m(),!(l!==t||t.state!=="prompt"))){t.state="loading",t.dialog.classList.remove("cosmos-prompt"),t.dialog.querySelector("#cosmos-title").textContent="Orbital notebook",t.dialog.querySelector(".cosmos-prompt-label").textContent="~/cosmos",t.host.innerHTML='<p class="cosmos-message" role="status">Opening a small universe\u2026</p>',t.dialog.querySelector(".cosmos-close").focus({preventScroll:!0});try{const e=new URL(c.dataset.cosmosModule,location.href);i&&e.searchParams.set("retry",String(i));const{mountPlayground:o}=await import(e.href);if(l!==t||t.abort.signal.aborted)return;t.playground=o({host:t.host,signal:t.abort.signal,onFatalError:()=>p(t)}),t.state="open"}catch{i++,p(t)}}}function h(){if(l)return;const t=m();t.dialog.querySelector(".cosmos-prompt-label").textContent="~/",t.host.innerHTML=`<form class="cosmos-command-form">
      <label for="cosmos-command">Enter a command</label>
      <div class="cosmos-command-row"><input id="cosmos-command" name="command" type="text"
        autocomplete="off" autocapitalize="none" spellcheck="false" required aria-describedby="cosmos-command-error">
        <button type="submit">Run</button></div>
      <p id="cosmos-command-error" role="status"></p></form>`;const e=t.host.querySelector("input");t.host.querySelector("form").addEventListener("submit",o=>{o.preventDefault(),e.value.trim().toLowerCase()==="cosmos"?(e.blur(),y(t)):t.host.querySelector("#cosmos-command-error").textContent="Unknown command."},{signal:t.abort.signal}),e.focus({preventScroll:!0})}function f(t){return t.composedPath().some(e=>e instanceof HTMLElement&&(e.isContentEditable||e.matches('input, textarea, select, [role="textbox"]')))}document.addEventListener("keydown",t=>{if(l||document.querySelector('dialog[open], [role="dialog"][aria-modal="true"]')||f(t)||t.isComposing||t.repeat||t.ctrlKey||t.metaKey||t.altKey){n();return}if(t.key==="Shift")return;if(!/^[a-z]$/i.test(t.key)){n();return}const e=performance.now();e-s>3e3&&(a=""),s=e,a=(a+t.key.toLowerCase()).slice(-6),a==="cosmos"&&(n(),y())}),window.addEventListener("blur",n),document.addEventListener("focusin",t=>{f(t)&&n()}),c.addEventListener("click",h),c.hidden=!1})();
